### ISSUE TITLE
Compositiehierachie <li>

### ISSUE THREAD

**Issue by lisavanmansom** [Akikosophia/look-and-feel-living-styleguide#1]
21 t/m 27 <il> inplaats van <li>

https://github.com/Akikosophia/look-and-feel-living-styleguide/blob/805e4f86eb2f7e161a8fe4d1ec4ffd4c51a3a0ad/Pages-html/compositiehierachie.html#L21-L27

**Comment by DamianR2004** [comment]
Opgelost, thanks!
