### ISSUE TITLE
Alt teksten

### ISSUE THREAD

**Issue by saschavanvliett** [Akikosophia/look-and-feel-living-styleguide#10]
https://github.com/Akikosophia/look-and-feel-living-styleguide/blob/2c3e4b7e30a9610ffc9067ec9c138c2cbe454ab5/Pages-html/Iconsbuttons.html#L134-L135

Miss de alt tekst hier meer specificeren want ze heten allebei 'button-code'.

**Comment by Hadil66** [comment]
![image](https://github.com/Akikosophia/look-and-feel-living-styleguide/assets/144008714/d75f01ff-805f-458e-a0c9-9ded028922cf)
