### ISSUE TITLE
Grote svg in .svg bestand

### ISSUE THREAD

**Issue by driezie** [Akikosophia/look-and-feel-living-styleguide#11]
https://github.com/Akikosophia/look-and-feel-living-styleguide/blob/2c3e4b7e30a9610ffc9067ec9c138c2cbe454ab5/Pages-html/Iconsbuttons.html#L68

bij deze voorbeelden kan je het beste een aparte bestand maken in bijvoorbeeld de img folder waarin je js svg in kan stoppen. Deze kan je op de pagina inladen door middel van een image tag en de link naar die svg bestand, zou houd je de code een heel stuk netter.

**Comment by Hadil24A** [comment]
Ik kan deze issue niet sluiten. Dit zijn de svg bestandjes die ze in de funda site ook gebruiken
