### ISSUE TITLE
Navigatie & interactie

### ISSUE THREAD

**Issue by Akikosophia** [Akikosophia/look-and-feel-living-styleguide#16]
Aan de zijkant wat ruimte tussen de tekst (padding)

**Comment by Abeeryu** [comment]
Ik heb een padding gebruikt om dat te fixen.

 padding: 30px;

![Screenshot 2023-11-17 112713](https://github.com/Akikosophia/look-and-feel-living-styleguide/assets/144008500/7952f950-7d8b-4a5b-a537-8a3b7800a8d4)
