### ISSUE TITLE
compositiehierachie li tag verkeerd

### ISSUE THREAD

**Issue by lisavanmansom** [Akikosophia/look-and-feel-living-styleguide#3]
verkeerd li tag

https://github.com/Akikosophia/look-and-feel-living-styleguide/blob/5c617dabb09d853761ba01ef5c02ba4bf7eeb4de/Pages-html/Vormen.html#L20C1-L26

**Comment by lisavanmansom** [comment]
is bij vormen html, in titel staat verkeerd , sorry!

**Comment by DamianR2004** [comment]
Opgelost, thanks#
