### ISSUE TITLE
Gebruik meer padding - Typografie

### ISSUE THREAD

**Issue by Abeeryu** [Akikosophia/look-and-feel-living-styleguide#7]
https://github.com/Akikosophia/look-and-feel-living-styleguide/blob/5c617dabb09d853761ba01ef5c02ba4bf7eeb4de/Pages-html/Typografie.html#L33-L60

Je moet een padding gebruiken om de kopjes te verdeling (witte ruimte te gebruiken)
Je kan deze link gebruiken om verder te werken aan jouw padding skills.

https://www.w3schools.com/css/css_padding.asp

**Comment by Akikosophia** [comment]
Gedaan!

**Comment by Akikosophia** [comment]
Gedaan!
