### ISSUE TITLE
Navigatie & Interactie

### ISSUE THREAD

**Issue by Hadil66** [Akikosophia/look-and-feel-living-styleguide#9]
Geen `<br>` gebruiken in de html, maar in de css de stijling toepassen

https://github.com/Akikosophia/look-and-feel-living-styleguide/blob/fe39268bf5e570abcbc0f2819f60052ccda564a9/Pages-html/navigatieinteractie.html#L36-L43

**Comment by Abeeryu** [comment]
Opgelost!
Ik heb margin gebruikt om dat om op te losson.

Css:

![Screenshot 2023-11-17 113737](https://github.com/Akikosophia/look-and-feel-living-styleguide/assets/144008500/bc9d088e-0286-4da8-9d9c-52687608f22d)

Html:

![Screenshot 2023-11-17 113824](https://github.com/Akikosophia/look-and-feel-living-styleguide/assets/144008500/9be20939-bb96-47a8-ab51-02be7366d448)
